POST http://localhost:3000/admin/
Content-Type: application/json

{
    "email":"fulano@gmail.com",
    "password":"123"

}
###
GET http://localhost:3000/api/26
Content-Type: application/json
Authorization: Bearer 123456789

{

}


###
POST http://localhost:3000/api/
Content-Type: application/json
Authorization: Bearer 123456789

{
    "nome": "fulano da silva nova",
    "telefone": "(00)00000-0000",
    "email": "fulano@gmail.com",
    "cep": "0000-000"
}

###
PUT http://localhost:3000/api/7
Content-Type: application/json
Authorization: Bearer 123456789

{
    "nome": "fulano da silva nova",
    "telefone": "(00)00000-0000",
    "email": "fulano@gmail.com",
    "cep": "0000-000"
}

###
DELETE  http://localhost:3000/api/7
Content-Type: application/json
Authorization: Bearer 123456789

{
  
}